
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-rec-f25-17
owner: ucsb-cs156-f25
repo_name: proj-rec-f25-17
pull_requests: [{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"preset-request-Types","number":11,"title":"hardcoded request types","url":"https://github.com/ucsb-cs156-f25/proj-rec-f25-17/pull/11"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"multiple-h2-Connections-v2","number":10,"title":"Multiple h2 connections v2","url":"https://github.com/ucsb-cs156-f25/proj-rec-f25-17/pull/10"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"request-types-Admins","number":8,"title":"Request types admins","url":"https://github.com/ucsb-cs156-f25/proj-rec-f25-17/pull/8"}]
